-- Stonixra POS Supabase schema
-- Run this full file in Supabase SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price decimal(10,2) not null,
  category text,
  stock integer default 0,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  loyalty_points integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text,
  customer_id bigint,
  total decimal(10,2),
  status text default 'Pending',
  order_type text,
  table_no text,
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint,
  product_id bigint,
  qty integer,
  price decimal(10,2)
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  email text,
  created_at timestamptz default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id bigint,
  item_name text,
  quantity integer default 0,
  unit text,
  updated_at timestamptz default now()
);

-- Single JSON state table used by this frontend demo version
create table if not exists public.pos_data (
  app text not null,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (app, key)
);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.staff enable row level security;
alter table public.inventory enable row level security;
alter table public.pos_data enable row level security;

-- Demo policies for frontend test. Replace with authenticated policies before production.
do $$
declare t text;
begin
  foreach t in array array['products','customers','orders','order_items','staff','inventory','pos_data'] loop
    execute format('drop policy if exists %I on public.%I', t||'_select_demo', t);
    execute format('drop policy if exists %I on public.%I', t||'_insert_demo', t);
    execute format('drop policy if exists %I on public.%I', t||'_update_demo', t);
    execute format('create policy %I on public.%I for select using (true)', t||'_select_demo', t);
    execute format('create policy %I on public.%I for insert with check (true)', t||'_insert_demo', t);
    execute format('create policy %I on public.%I for update using (true) with check (true)', t||'_update_demo', t);
  end loop;
end $$;
